version: '3.3'
services:
  jetson-detectnet:
    build: .
    image: jetson-detectnet:0.0.1
    container_name: jetson-detectnet
    runtime: nvidia
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=:0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    privileged: true